#!/usr/bin/env python
# Copyright (c) 2012 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Prints the untracked files."""

import os
import sys

import find_depot_tools

import subprocess2

try:
  cwd = subprocess2.check_output(
      ['git', 'rev-parse', '--show-cdup']).strip()
  output = subprocess2.check_output(
      ['git', 'clean', '-n', '-d'],
      cwd=os.path.abspath(cwd))
  prefix = 'Would remove '
  for line in output.splitlines():
    assert line.startswith(prefix)
    print line[len(prefix):]
except subprocess2.CalledProcessError, e:
  sys.exit(e.returncode)
